title: "Your Name"
email: you@example.com
description: "A portfolio and blog about my research and interests."
baseurl: ""              # leave empty for username.github.io
url: "https://username.github.io"

# Markdown & math
markdown: kramdown
kramdown:
  math_engine: katex
  math_aliases:
    inline: ["$", "$"]
    display: ["$$","$$"]

# Build settings
plugins:
  - jekyll-feed          # optional feed

collections:
  posts:
    output: true